### ISSUE TITLE
Pypi Release

### ISSUE THREAD

**Issue by bartTC** [django-cms/djangocms-transfer#28]
Hi, this app has seen a lot of fixes but no pypi release in 3 years. Can you create a v1.1? 

Thank you!

**Comment by fsbraun** [comment]
@marksweb I could add the pypi actions and trigger a release. What do you think?

**Comment by marksweb** [comment]
@fsbraun yeah makes sense 👍

**Comment by bartTC** [comment]
Any chance to do at least a pre release with the current state, that is compatible with Django 4.x?

**Comment by fsbraun** [comment]
@bartTC Thanks for the reminder! Here's the release: https://pypi.org/project/djangocms-transfer/
