### ISSUE TITLE
After installing, any command ran from manage.py brings up an error

### ISSUE THREAD

**Issue by Leyght811** [django-cms/djangocms-transfer#37]
After installing djangocms-transfer i tried to run `python manage.py migrate djangocms_transfer` as stated in the readme.  This brought up the following error `ImportError: cannot import name 'reorder_plugins' from 'cms.utils.plugins' (.../venv/lib/python3.12/site-packages/cms/utils/plugins.py)
`
This error also occurs whenever I try to run other commands from manage.py e.g: `python manage.py runserver`, or `python manage.py version`
Details:
Python version 3.12
Django version 5.0.1
Django cms version 4.1.0

**Comment by greyhare** [comment]
Please update README to show incompatibility with CMS 4.

Like several other packages on https://www.django-cms.org/en/repositories-plugins/, there is no indication anywhere as to which packages are or aren't compatible with 4.x. They're all "recommended" on that page and "endorsed by the django CMS Association" in the README.

**Comment by fsbraun** [comment]
@greyhare A release of v2.0.0alpha is imminent: It brings django CMS 4 support.

**Comment by fsbraun** [comment]
@greyhare @Leyght811 `djangocms-transfer==2.0.0a0` does work with django CMS. This is an alpha-release. Please report back any issues.
